#!/data/data/com.termux/files/usr/bin/python
import os,sys
try:
    import phonenumbers
except:
    os.system("pip install phonenumbers")
    import phonenumbers
import time as tm
from phonenumbers import geocoder,timezone,carrier
os.system("clear")

# Main Bammer .....
logo="""\a\a\n\33[32;1m
    _   __                ____      ____
   / | / /_  ______ ___  /  _/___  / __/___
  /  |/ / / / / __ `__ \ / // __ \/ /_/ __ \.
 / /|  / /_/ / / / / / // // / / / __/ /_/ /
/_/ |_/\__,_/_/ /_/ /_/___/_/ /_/_/  \____/
\33[0m                          ~created by Alienkrishn
\33[35m                           Github:Anon4You\33[0m
"""
# Small banner......
smlogo="""\33[31;1m
     ▙ ▌       ▜▘   ▗▀▖
     ▌▌▌▌ ▌▛▚▀▖▐ ▛▀▖▐  ▞▀▖
     ▌▝▌▌ ▌▌▐ ▌▐ ▌ ▌▜▀ ▌ ▌
     ▘ ▘▝▀▘▘▝ ▘▀▘▘ ▘▐  ▝▀\33[0m
phone number information gathering tool
----------------------------------------"""
print(logo)

# taking input from user 
number=input("Enter_Number: ")

# this will print letters 1 by 1
def rprint(s):
    for anon in s + '\n':
        sys.stdout.write(anon)
        sys.stdout.flush()
        tm.sleep(0.01)

# using module phonenumbers
phone=phonenumbers.parse(number)
vlid=phonenumbers.is_valid_number(phone)
carr=carrier.name_for_number(phone,"en")
time=timezone.time_zones_for_number(phone)
regn=geocoder.description_for_number(phone,"en")

# printing all information
os.system("clear")
print(smlogo)
print("\33[32mFetching information please wait\n")
tm.sleep(2)
print(phone)
rprint("\33[33m-----------------------------------------\33[0m")
print("Is this number valid : ",vlid)
rprint("\33[33m-----------------------------------------\33[0m")
print("Carrier : ",carr)
rprint("\33[33m-----------------------------------------\33[0m")
print("Timezone : ",time)
rprint("\33[33m-----------------------------------------\33[0m")
print("Region : ",regn)
rprint("\33[33m-----------------------------------------\33[0m")
print("\n\33[35mScan finished....")

